# Generated by Django 4.1.7 on 2023-05-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='adult_rating',
            field=models.CharField(default='no', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default='en', max_length=255),
            preserve_default=False,
        ),
    ]
